'aaafaxis=const(lev,0.0)'
'set gxout contour'
'set xlpos 0 t'
'set ylpos 0 r'
'set clab off'
'set clevs -1e+15'
'set grads off'
'd aaafaxis'
'undefine aaafaxis'
'set xlpos 0 b'
'set ylpos 0 l'
'set clab on'
